name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures a full clone for accurate SonarQube analysis
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://10.1.1.228:9000"  # Set to your Raspberry Pi SonarQube IP

      - name: Debug SonarQube Scan
        run: |
          sonar-scanner -X \
            -Dsonar.projectKey=my-github-project \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://10.1.1.228:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      
      # If you want to fail the job when the Quality Gate fails, uncomment below
      # - name: SonarQube Quality Gate
      #   uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
